### ISSUE TITLE
[feature] Use Discourse as SSO provider

### ISSUE THREAD

**Issue by jrgong420** [vikaspotluri123/discourse-on-ghost#220]
I am looking for possibility to offer a button to use Discourse as SSO provider for my ghost instance.
Is that possible?

**Comment by vikaspotluri123** [comment]
I'm pretty hesitant that discourse-on-ghost (Discourse [auth] is built on Ghost) should also support ghost-on-discourse (Ghost [auth] is built on Discourse); I think it would add a lot of complexity to the project Moreover, Ghost's staff auth system doesn't have stable SSO support, and members auth is completely separate from staff auth. 

If you're looking for members SSO, there's a [service](https://www.spectralwebservices.com/blog/social-sign-on-for-ghost/) that supports social sign-on - I'm not sure if they're willing to add [Discourse support](https://meta.discourse.org/t/use-discourse-as-an-identity-provider-sso-discourseconnect/32974)
